name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jahentao/faas-idler:latest
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: jahentao/faas-idler
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tag script: |
          return context.ref
            .replace('refs/heads/
            .replace('refs/tags/'
            .replace('refs/pull/'
            .replace(/\//g, '_')
            .replace(/#/g, '');
        #registry: localhost:8080      
